### ISSUE TITLE
Stylish Extension stealing data

### ISSUE THREAD

**Issue by NilsRethmeier** [burglarbenson/Jupyter-Atom-Dark-Theme#1]
Source: https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/

You might want to recommend the [Stylus extension](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) . Stylish  Extension without the track/ad-ware -- for now.

**Comment by burglarbenson** [comment]
Thanks for linking that - wasn't aware of Stylus so have updated the install readme. Cheers!
