### ISSUE TITLE
Text editor still white

### ISSUE THREAD

**Issue by pdeffebach** [burglarbenson/Jupyter-Atom-Dark-Theme#2]
This is fantastic! thanks. 

One thing: it looks like the text editor for jupyterlab is still white. The atom color scheme doesn't seem to apply to that.

**Comment by burglarbenson** [comment]
Hadn't spotted that, don't use the text editor on Jupyter Lab much! Checked in an update.

**Comment by pdeffebach** [comment]
thanks! ill redownload
